apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdepl
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 45
  selector:  
   matchLabels:
    app: nginx1
  template:
    metadata:
      name: nginxsvc
      labels:
        app: nginx1 
    spec:
     containers:    
     - name: nginxpod
       image: nginx:1.18
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort   
  selector:
    app: nginx1
  ports:
  - port: 80   
    targetPort: 80    
              
