apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  selector:  
    matchLabels:      
      app: javawebapp
  strategy:
    type: Recreate
  template:  
    metadata:
      name: javawebappod       
      labels:  
        app: javawebapp
    spec:
      containers:     
      - name: javawebappcontianer
        image: dockerhandson/java-web-app:2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80       
    targetPort: 8080

