apiVersion: v1
kind: Pod
metadata:
  name: nginxapp1
  labels:
    app: mynginx
spec:
  containers:
  - name: myfirstpod1
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: ClusterIP
  selector:
    app: mynginx
  ports:
  - port: 80
    targetPort: 80
