apiVersion: v1
kind: Pod
metadata: 
  name: javawebappod
  labels:
    app: javawebapp
spec: 
  containers:
  - name: javawebappcontainer
    image: dockerhandson/java-web-app
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc  
spec:  
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80        
    targetPort: 8080

