apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainerrs
        image: dockerhandson/java-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80      
    targetPort: 8080  


